name: M3U Playlist Processor

on:
  schedule:
    - cron: '0 0 * * 1' # Daily schedule
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download and concatenate m3u files for iplive
      run: |
        curl https://assets.livednow.com/epg.xml > epg.xml
        curl https://raw.githubusercontent.com/shdejavu/epg/master/guide.xml >jp.xml
        python epgmerge.py

    - name: Run M3U processing script
      run: |
        python nm3u.py

    - name: Download and concatenate m3u files for iplive
      run: |
        curl https://iptv-org.github.io/iptv/languages/zho.m3u > zho.m3u
        curl https://iptv-org.github.io/iptv/languages/jpn.m3u > jpn.m3u
        curl https://iptv-org.github.io/iptv/languages/eng.m3u > eng.m3u
        curl https://iptv-org.github.io/iptv/languages/undefined.m3u > undefined.m3u
        cat zho.m3u jpn.m3u eng.m3u undefined.m3u > iplive.m3u
        
    - name: Run JP script
      run: |
        curl https://raw.githubusercontent.com/shdejavu/epg/master/guide.xml >jp.xml
        grep -A1 '.jp"' combined_cleaned.m3u >jp.m3u
        python grouptitle.py
        python tvgname.py
        cat itv_p.m3u migu.m3u all0.m3u jp.m3u >allback.m3u
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git add guide.xml
        git add combined_cleaned.m3u iplive.m3u migu.m3u jp.m3u allback.m3u
        git commit -m "Update m3u files with processed data"
        git push
