name: M3U Playlist Processor

on:
  schedule:
    - cron: '0 0 * * 1' # Daily schedule
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run M3U processing script
      run: |
        python nm3u.py

    - name: Download and concatenate m3u files for iplive
      run: |
        curl https://raw.githubusercontent.com/iptv-org/iptv/refs/heads/master/streams/jp.m3u > jp.m3u
        curl https://raw.githubusercontent.com/iptv-org/iptv/refs/heads/master/streams/jp_primehome.m3u > jp2.m3u
        curl https://raw.githubusercontent.com/iptv-org/iptv/refs/heads/master/streams/cn.m3u > cn.m3u
        curl https://raw.githubusercontent.com/iptv-org/iptv/refs/heads/master/streams/us.m3u > us.m3u
        cat cn.m3u jp.m3u jp2.m3u us.m3u> iplive.m3u
        
    - name: Run JP script
      run: |
        grep -A1 '.jp"' combined_cleaned.m3u >jp.m3u
        python grouptitle.py
        python tvgname.py
        cat itv_p.m3u migu.m3u all0.m3u jp.m3u >allback.m3u
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git add combined_cleaned.m3u iplive.m3u migu.m3u jp.m3u allback.m3u
        git commit -m "Update m3u files with processed data"
        git push
